---
abstract: 'POD viewer for QBit application'
author:
  - 'Sergei Svistunov <sergei-svistunov@yandex.ru>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: QBit-WebInterface-Controller-Pod
requires:
  Pod::Checker: 0
  Pod::Simple::HTML: 0
  QBit::Application::Model: 0
  QBit::WebInterface::Controller: 0
  base: 0
  qbit: 0
  strict: 0
  warnings: 0
version: 0.004
